import type {
  User,
  Customer,
  Account,
  Card,
  Transaction,
  DisclosureGroup,
  TransactionType,
  TransactionCategory,
  CategoryBalance,
} from '../types';

export const mockUsers: User[] = [
  {
    user_id: 'ADMIN001',
    password: '********',
    user_type: 'Administrator',
    first_name: 'John',
    last_name: 'Smith',
    last_login: new Date('2025-11-16T14:30:00'),
    account_status: 'Active',
  },
  {
    user_id: 'USER001',
    password: '********',
    user_type: 'Customer Service',
    first_name: 'Jane',
    last_name: 'Doe',
    last_login: new Date('2025-11-17T09:15:00'),
    account_status: 'Active',
  },
  {
    user_id: 'USER002',
    password: '********',
    user_type: 'Supervisor',
    first_name: 'Bob',
    last_name: 'Johnson',
    last_login: new Date('2025-11-15T16:45:00'),
    account_status: 'Active',
  },
];

export const mockCustomers: Customer[] = [
  {
    customer_id: 'CUST000001',
    first_name: 'Alice',
    middle_name: 'Marie',
    last_name: 'Williams',
    address_line1: '123 Main Street',
    address_line2: 'Apt 4B',
    city: 'New York',
    state: 'NY',
    zip_code: '10001',
    country: 'USA',
    phone_number: '212-555-0123',
    email: 'alice.williams@email.com',
    ssn: '***-**-1234',
    date_of_birth: new Date('1985-03-15'),
    credit_rating: 'A+',
    created_date: new Date('2020-01-10'),
    updated_date: new Date('2025-11-01'),
  },
  {
    customer_id: 'CUST000002',
    first_name: 'Robert',
    last_name: 'Chen',
    address_line1: '456 Oak Avenue',
    city: 'San Francisco',
    state: 'CA',
    zip_code: '94102',
    country: 'USA',
    phone_number: '415-555-0198',
    email: 'robert.chen@email.com',
    ssn: '***-**-5678',
    date_of_birth: new Date('1990-07-22'),
    credit_rating: 'A',
    created_date: new Date('2021-05-20'),
    updated_date: new Date('2025-10-15'),
  },
];

export const mockAccounts: Account[] = [
  {
    account_id: 'ACCT000001',
    customer_id: 'CUST000001',
    account_number: '4532-1234-5678-9012',
    account_type: 'Credit',
    account_status: 'Active',
    current_balance: 2500.50,
    credit_limit: 10000.00,
    available_credit: 7499.50,
    cash_advance_limit: 3000.00,
    interest_rate: 18.99,
    disclosure_group: 'DISC001',
    account_open_date: new Date('2020-01-15'),
    last_statement_date: new Date('2025-11-01'),
    past_due_amount: 0,
    days_past_due: 0,
  },
  {
    account_id: 'ACCT000002',
    customer_id: 'CUST000002',
    account_number: '5412-9876-5432-1098',
    account_type: 'Credit',
    account_status: 'Active',
    current_balance: 5432.10,
    credit_limit: 15000.00,
    available_credit: 9567.90,
    cash_advance_limit: 5000.00,
    interest_rate: 15.99,
    disclosure_group: 'DISC002',
    account_open_date: new Date('2021-06-01'),
    last_statement_date: new Date('2025-10-28'),
    past_due_amount: 0,
    days_past_due: 0,
  },
];

export const mockCards: Card[] = [
  {
    card_number: '4532123456789012',
    account_id: 'ACCT000001',
    card_type: 'Visa',
    card_status: 'Active',
    cardholder_name: 'ALICE M WILLIAMS',
    issue_date: new Date('2020-01-15'),
    expiration_date: new Date('2027-01-31'),
    cvv: '***',
    pin: '****',
    last_used_date: new Date('2025-11-16'),
    failed_pin_attempts: 0,
  },
  {
    card_number: '5412987654321098',
    account_id: 'ACCT000002',
    card_type: 'Mastercard',
    card_status: 'Active',
    cardholder_name: 'ROBERT CHEN',
    issue_date: new Date('2021-06-01'),
    expiration_date: new Date('2026-06-30'),
    cvv: '***',
    pin: '****',
    last_used_date: new Date('2025-11-17'),
    failed_pin_attempts: 0,
  },
];

export const mockTransactions: Transaction[] = [
  {
    transaction_id: 'TXN000001',
    account_id: 'ACCT000001',
    card_number: '4532123456789012',
    transaction_type: 'PURCH',
    transaction_category: 'RETAIL',
    transaction_date: new Date('2025-11-16T10:30:00'),
    transaction_amount: 125.50,
    merchant_name: 'Target Store #1234',
    merchant_city: 'New York',
    merchant_zip: '10001',
    description: 'Purchase',
    post_status: 'Posted',
    post_date: new Date('2025-11-17'),
    authorization_code: 'AUTH123456',
    currency_code: 'USD',
    exchange_rate: 1.0,
  },
  {
    transaction_id: 'TXN000002',
    account_id: 'ACCT000001',
    card_number: '4532123456789012',
    transaction_type: 'PURCH',
    transaction_category: 'DINING',
    transaction_date: new Date('2025-11-15T19:45:00'),
    transaction_amount: 85.75,
    merchant_name: 'Italian Restaurant',
    merchant_city: 'New York',
    merchant_zip: '10002',
    description: 'Dinner',
    post_status: 'Posted',
    post_date: new Date('2025-11-16'),
    authorization_code: 'AUTH123457',
    currency_code: 'USD',
    exchange_rate: 1.0,
  },
  {
    transaction_id: 'TXN000003',
    account_id: 'ACCT000002',
    card_number: '5412987654321098',
    transaction_type: 'PURCH',
    transaction_category: 'TRAVEL',
    transaction_date: new Date('2025-11-17T08:15:00'),
    transaction_amount: 450.00,
    merchant_name: 'United Airlines',
    merchant_city: 'San Francisco',
    merchant_zip: '94102',
    description: 'Flight Ticket',
    post_status: 'Pending',
    authorization_code: 'AUTH123458',
    currency_code: 'USD',
    exchange_rate: 1.0,
  },
];

export const mockDisclosureGroups: DisclosureGroup[] = [
  {
    disclosure_group: 'DISC001',
    group_name: 'Standard Credit Card Terms',
    description: 'Standard terms for credit card accounts',
    terms_conditions: 'Standard APR 18.99%, No annual fee, Grace period 25 days...',
    disclosure_text: 'Your Annual Percentage Rate (APR) for purchases is 18.99%...',
  },
  {
    disclosure_group: 'DISC002',
    group_name: 'Premium Credit Card Terms',
    description: 'Premium terms with rewards',
    terms_conditions: 'Standard APR 15.99%, Annual fee $95, Grace period 25 days...',
    disclosure_text: 'Your Annual Percentage Rate (APR) for purchases is 15.99%...',
  },
];

export const mockTransactionTypes: TransactionType[] = [
  {
    type_code: 'PURCH',
    type_description: 'Purchase',
    debit_credit_indicator: 'Debit',
    category_code: 'RETAIL',
  },
  {
    type_code: 'PAYMENT',
    type_description: 'Payment',
    debit_credit_indicator: 'Credit',
    category_code: 'PAYMNT',
  },
  {
    type_code: 'CASH',
    type_description: 'Cash Advance',
    debit_credit_indicator: 'Debit',
    category_code: 'CASH',
  },
  {
    type_code: 'FEE',
    type_description: 'Fee',
    debit_credit_indicator: 'Debit',
    category_code: 'FEES',
  },
  {
    type_code: 'INTEREST',
    type_description: 'Interest Charge',
    debit_credit_indicator: 'Debit',
    category_code: 'INTRST',
  },
];

export const mockTransactionCategories: TransactionCategory[] = [
  {
    category_code: 'RETAIL',
    category_name: 'Retail',
    category_description: 'Retail purchases',
    category_group: 'Shopping',
  },
  {
    category_code: 'DINING',
    category_name: 'Dining',
    category_description: 'Restaurants and dining',
    category_group: 'Food & Drink',
  },
  {
    category_code: 'TRAVEL',
    category_name: 'Travel',
    category_description: 'Travel and transportation',
    category_group: 'Travel',
  },
  {
    category_code: 'GAS',
    category_name: 'Gas Station',
    category_description: 'Fuel and gas purchases',
    category_group: 'Automotive',
  },
  {
    category_code: 'GROCERY',
    category_name: 'Groceries',
    category_description: 'Grocery store purchases',
    category_group: 'Food & Drink',
  },
];

export const mockCategoryBalances: CategoryBalance[] = [
  {
    account_id: 'ACCT000001',
    category_code: 'RETAIL',
    balance_date: new Date('2025-11-01'),
    category_balance: 850.25,
    transaction_count: 12,
    average_transaction: 70.85,
    max_transaction: 250.00,
    min_transaction: 15.50,
    last_updated: new Date('2025-11-17'),
  },
  {
    account_id: 'ACCT000001',
    category_code: 'DINING',
    balance_date: new Date('2025-11-01'),
    category_balance: 425.75,
    transaction_count: 8,
    average_transaction: 53.22,
    max_transaction: 125.00,
    min_transaction: 25.00,
    last_updated: new Date('2025-11-17'),
  },
];
